### ISSUE TITLE
How to enable support for M66 - M66FAR02A08BT?

### ISSUE THREAD

**Issue by bkrajendra** [Wiz-IO/platformio-quectel-examples#12]
Hi
It's really great to see this platform port for quectel modules.
I am using the latest firmware, can you guide me on how can I enable support for M66  M66FAR02A08BT.

I can contribute back if it's possible to form me.

**Comment by Wiz-IO** [comment]
Hi
M66 Arduino work only with M66FAR01A12BT1
For OpenCPU must work for all firmwares

Regards
