### ISSUE TITLE
pull up for the AWS iot cloud connection

### ISSUE THREAD

**Issue by nices0325** [Wiz-IO/platformio-quectel-examples#13]
can you let me know simple example of how to connect to AWS iot cloud (e.g. shadow things) with quectel bg96 module??
It's a little bit hard for me to connect to AWS iot cloud using bg96 mqtt library... thank you

**Comment by Wiz-IO** [comment]
https://github.com/globaledgesoft/merchant-cart-aws-iot

**Comment by nices0325** [comment]
thank you very much sir
