### ISSUE TITLE
kindly give some gpio and adc examples for arduino platform for BG96

### ISSUE THREAD

**Issue by Dineshkumar-code** [Wiz-IO/platformio-quectel-examples#15]
kindly give some gpio and adc examples of arduino platform for BG96

**Comment by Wiz-IO** [comment]
gpio is as arduino
adc - open read... look code wiringAnalog

**Comment by Wiz-IO** [comment]
pinMode(1, OUTPUT)
digitalWrite(1, 1/0 )

pin table:
https://github.com/Wiz-IO/framework-quectel/blob/cde22553e012cafd72b22c7c593bf0ef99307c11/arduino/variants/bg96/variant_pins.c#L8

analogOpen(0);
val = analogRead(0);

pin table:
https://github.com/Wiz-IO/framework-quectel/blob/master/arduino/cores/bg96/wiring_analog.c#L32

**Comment by Dineshkumar-code** [comment]
while using
analogOpen(0);
val = analogRead(0);

like that above I am getting restart problem on bg96 dev module  is any solution for that

**Comment by Wiz-IO** [comment]
no idea ... debug code
or ask Quectel support - the Arduino use QuecOpen API

**Comment by Dineshkumar-code** [comment]
it's reset and goes on void setup over some period, driver get disable and enable occur..
any solution for that

**Comment by Dineshkumar-code** [comment]
any solution for that

**Comment by Wiz-IO** [comment]
firmware BG96MA**R02**A09M1G_01.011.01.011 ( recommended )

**Comment by Dineshkumar-code** [comment]
Where to get the firmware version

**Comment by Wiz-IO** [comment]
https://www.quectel.com/contact/

**Comment by Dineshkumar-code** [comment]
Sir, How to solve restart issue on BG96 MA, kindly give some idea, that may helpful for me

**Comment by Dineshkumar-code** [comment]
> https://www.quectel.com/contact/

They is no response from Quectel, Is possible to get firmware version from you...

**Comment by Wiz-IO** [comment]
https://forums.quectel.com/
I am not authorized to share Quectel tools

**Comment by Dineshkumar-code** [comment]
ok Sir

**Comment by Wiz-IO** [comment]
or contact with your local Quectel support

**Comment by Dineshkumar-code** [comment]
I got same firmware version but GPIO's are  not controllable as mentioned GPIO  mapping,  adc reading same restart issue occur.

**Comment by Wiz-IO** [comment]
debug code or use QuecOpen API ( ThreadX API )

**Comment by Dineshkumar-code** [comment]
PIN NUM,     PIN NAME,    GPIO ID  GPIO FUNC which one i want to use and control gpio on bg96 arduino platform

**Comment by Dineshkumar-code** [comment]
> debug code or use QuecOpen API ( ThreadX API )


#include <Arduino.h>
#include <variant.h>
#include <wiring_analog.c>
#define pin_num 1
void setup() {
  Serial1.begin(115200);
  Serial1.println("inside Initialization");
  pinMode(pin_num,INPUT);
  analogOpen(pin_num);
    // put your setup code here, to run once:
}

void loop() {
  
int val  = analogRead(1);
Serial1.println("val : ");
Serial1.println(val);

  
  //delay(1000);
 // Serial1.println(val);
  // put your main code here, to run repeatedly:
}



then the module get restarting on bg96

**Comment by Wiz-IO** [comment]
loop() must end with delay(1) as yield... it is RTOS

**Comment by Dineshkumar-code** [comment]
okay

**Comment by Dineshkumar-code** [comment]
i dont have SDK325 is a problem to use threadx method without that..

**Comment by Wiz-IO** [comment]
BG96MAR0**2**... is SDK2
Arduino here support only SDK2

SDK3 & 4 have MMU enabled

**Comment by Dineshkumar-code** [comment]
can I get  any docs or videos for controlling gpio using threadx method for BG96

**Comment by Wiz-IO** [comment]
ask from your local Quectel support QuecOpen/ThreadX SDK ... there is examples and documentation
