### ISSUE TITLE
facing problem in fetching data

### ISSUE THREAD

**Issue by m2c-chandan** [Wiz-IO/platformio-quectel-examples#16]
hello sir, 
I am trying the example code of MC60 which is about SPI flash interface but I don't know how to communicate with q navigator using UART what input do I have to send to get communication started, as for now I was sending these inputs but its saying not found your command please check your command, please help me with this I am stuck here. 
Thank you

 *            
 *     If input "Ql_SPI_Init", that will init the SPI channel.
 *     If input "Ql_SPI_Config", that will configure the SPI parameter.
 *     If input "Ql_SPI_Write", that will write bytes to slave equipment through SPI interface.
 *     If input "Ql_SPI_Read", that will read bytes from slave equipment through SPI interface.
 *     If input "Ql_SPI_WriteRead", that will read and write bytes through SPI interface.
 *     If input "Ql_SPI_Uninit", that will release the SPI pins.

**Comment by Wiz-IO** [comment]
Hi
About OpenCPU, please connect with Quectel support

**Comment by m2c-chandan** [comment]
Ohk, I have posted there as well
