### ISSUE TITLE
atfwd example compile error

### ISSUE THREAD

**Issue by devwoojin** [Wiz-IO/platformio-quectel-examples#3]
platformio-quectel-examples/ThreadX/bg96/atfwd

Terminal will be reused by tasks, press any key to close it.

> Executing task: C:\.platformio\penv\Scripts\platformio.exe run <

Processing bg96 (platform: quectel; board: bg96; framework: threadx)
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
<<<<<<<<<<<< QUECTEL BG96 MODULE 2018 Georgi Angelov >>>>>>>>>>>>
CONFIGURATION: https://docs.platformio.org/page/boards/quectel/bg96.html
PLATFORM: Quectel 2.0.14 #ba06662 > Quectel BG96 module
HARDWARE: ARM, MDM9206 1200MHz, 3.00MB RAM, 3.00MB Flash
DEBUG: Current (uart) On-board (uart)
PACKAGES: framework-quectel 02002ee, toolchain-gccarmnoneeabi 1.70201.0 (7.2.1)
CORE bg96 SDK2 RO_BASE = 0x40000000 HEAP = 1048576
LDF: Library Dependency Finder -> http://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 0 compatible libraries
Scanning dependencies...
No dependencies
Building in release mode
Compiling .pio\build\bg96\src\main.o
Linking .pio\build\bg96\program.elf
.pio\build\bg96\src\main.o: In function `TXM_MODULE_THREAD_ENTRY':
main.c:(.library+0x4c): undefined reference to `qapi_atfwd_Pass_Pool_Ptr'
collect2.exe: error: ld returned 1 exit status
*** [.pio\build\bg96\program.elf] Error 1
========================================================================================== [FAILED] Took 2.98 seconds ==========================================================================================
The terminal process terminated with exit code: 1

Terminal will be reused by tasks, press any key to close it.

there are two qapi_atfwd.h 
bg96>SKD2>qapi>qapi_atfwd.h
bg96>SKD424>qapi>qapi_atfwd.h

**Comment by Wiz-IO** [comment]
the examples is from SDK3 and must be valid for SDK4

SDK2 not have qapi_atfwd_Pass_Pool_Ptr, 
if you have SDK2 archive - get example from there or ask from Quectel

**Comment by devwoojin** [comment]
quectel eval board + BG96 + PlatformIO

ATI
Quectel
BG96
Revision: BG96MAR02A07M1G

OK

patformio.ini
[env:bg96]
platform = quectel
board = bg96
framework = threadx
upload_port = COM26


threadx-bg96.py
....
def dev_init(env, platform):
    dev_create_template(env)
    dev_compiler(env)
    framework_dir = env.PioPlatform().get_package_dir("framework-quectel")
    core = env.BoardConfig().get("build.core") 
    env.sdk = env.BoardConfig().get("build.sdk", "SDK2").upper()  #SDK2 #SDK2831 #SDK325 #SDK424 

the default main.c only works SDK2 , SDK2831
SDK325, SDK424 build, upload success but not work.

**Comment by Wiz-IO** [comment]
are you switch SDK from platformio.ini
;board_build.sdk =  ; empty is SDK2, other SDK2831 SDK325 SDK424

**Comment by Wiz-IO** [comment]
btw: you can not use SDK3/4 with BG96MA**R02**A07M1G
SDK3 is for ...RA3...

https://github.com/Wiz-IO/platform-quectel/wiki/Framework-ThreadX#firmwares-and-quectel-bg96-threadx-sdk

**Comment by devwoojin** [comment]
thank you..^^
