### ISSUE TITLE
Can's find an example of SMS

### ISSUE THREAD

**Issue by smartechru** [Wiz-IO/platformio-quectel-examples#4]
Thank you for your great work!
I have installed Quectel BG96 SDK and could build all the example projects successfully.
I am going to process commands via SMS or UART. Unfortunately, I couldn't get any idea how to deal with them. If you have an example for that, could you please share it?
I really appreciate it. Thanks in advance.

Regard.

**Comment by Wiz-IO** [comment]
Hi, thanks...
maybe your question is for here https://forums.quectel.com/ :)

**Comment by smartechru** [comment]
Will do. Thank you. :)

**Comment by smartechru** [comment]
I've finished it :)
