### ISSUE TITLE
Example_timer crashes before timer expires

### ISSUE THREAD

**Issue by ASL07** [Wiz-IO/platformio-quectel-examples#6]
The https://github.com/Wiz-IO/platformio-quectel-examples/blob/master/BC66_SDK/OpenCPU/example_timer.c example crashes with the following input when using BC66NBR01A10 & SDK v1.5 . Board is Olimex BC66 devkit

I have done other tests and I am not able to make the timer api work

```
<--OpenCPU: Timer TEST!-->

<--Register: timerId=258, param = 0,ret = 0 -->

<--RegisterFast: timerId=257, param = 0,ret=0 -->

F1: 0000 0000
V0: 0000 0000 [0001]
00: 0006 000C
01: 0000 0000
U0: 0000 0001 [0000]
T0: 0000 00B4

```

**Comment by Wiz-IO** [comment]
copy ... paste

![Untitled-1](https://user-images.githubusercontent.com/14574834/76542128-3aed0680-648d-11ea-814c-de962a5657be.jpg)

**Comment by Wiz-IO** [comment]
BTW: All folder is Quectel examples from SDK  ( copy-paste to git )
I not make any modifications...
