### ISSUE TITLE
LwM2M example

### ISSUE THREAD

**Issue by probonopd** [Wiz-IO/platformio-quectel-examples#7]
Would it be possible to add a LwM2M example for Arduino please? As far as I understand, the LwM2M functionality is provided by Quectel. An example how to use it would be very helpful. Thank you very much for this useful project.

**Comment by Wiz-IO** [comment]
Hi
I not have LwM2M server for experiments and tests

**Comment by probonopd** [comment]
Hi @Wiz-IO and thanks for your very quick response.

Maybe you can use the Leshan Server Sandbox? it's open source and they provide a free hosted instance for testing:

> In order to help you test your LWM2M solutions quickly, the Leshan project provides a Lightweight M2M standalone server you can freely connect to for evaluation purposes.

https://github.com/eclipse/leshan#test-server-sandbox

Thanks for your consideration.

**Comment by Wiz-IO** [comment]
Thanks, will test soon

**Comment by Wiz-IO** [comment]
do you understand from wakaama client?

**Comment by probonopd** [comment]
Unfortunately I have no experience with it. But I think that Wakaama imlpements a LwM2M client in software, whereas the Quectel modules and code have their own LwM2M client?

**Comment by Wiz-IO** [comment]
yes, I can extract ( static lib ) with internal Wakaama client for experiments

**Comment by Wiz-IO** [comment]
![Untitled-1](https://user-images.githubusercontent.com/14574834/77223784-4e246400-6b68-11ea-88fb-9ecda5cc1ecf.jpg)

**Comment by Wiz-IO** [comment]
![Untitled-2](https://user-images.githubusercontent.com/14574834/77223874-1c5fcd00-6b69-11ea-9d49-7e8d0f15034c.jpg)
