### ISSUE TITLE
Examples outdated?

### ISSUE THREAD

**Issue by Savjee** [Wiz-IO/platformio-quectel-examples#8]
Hi,

I just got the Olimex NB-IoT-DevKit and trying out your quectel platform. Unfortunately I'm unable to get the examples to work.

The `get_info` example gives me this error:
```
src/main.cpp: In function 'void setup()':
src/main.cpp:20:42: error: 'class LDEV' has no member named 'getVersion'; did you mean 'version'?
```

Changing it to `version` gives me additional errors:

```
src/main.cpp:26:7: error: 'class LDEV' has no member named 'waitSimReady'
   Dev.waitSimReady();
```

I tried other examples as well. The `https_internal` example complains about not finding `#include <nbHttpClient.h>`.

Any thoughts?
Using the latest version of the framework with Platform.io
Thanks!

**Comment by Wiz-IO** [comment]
https://github.com/Wiz-IO/platformio-quectel-examples/tree/master/BC66_SDK

**Comment by Savjee** [comment]
Ah, I was looking in the wrong directory. Thanks for pointing me in the right direction.

Any pointers on how I could send UDP packets to AllThingsTalk? https://docs.allthingstalk.com/developers/api/udp-messaging/

Or, alternatively, how to set the headers of HTTP requests?

**Comment by Wiz-IO** [comment]
Arduino as Arduino? https://docs.allthingstalk.com/examples/kits/arduino-rdk/
OpenCPU ( ask Quectel Support )

my API https://github.com/Wiz-IO/framework-quectel/blob/master/opencpu/bc66/SDK15/wizio/os_api.h#L101
find examples about this (is the same)
https://github.com/andornotlee/sdk4.2.2/tree/master/middleware/third_party/httpclient

**Comment by Savjee** [comment]
Appreciate your help!
Great job with this platform ;)
